import json
from typing import TypedDict

from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, ValidationError


class DebateWorkflowState(TypedDict):
    proposal: str
    status: str
    events: list[dict]


class DecisionReport(BaseModel):
    decision: str
    confidence: str
    note: str


def _parse_report_with_retry(outputs: list[str]) -> tuple[DecisionReport, bool]:
    for idx, raw in enumerate(outputs):
        try:
            parsed = DecisionReport.model_validate(json.loads(raw))
            return parsed, idx > 0
        except (json.JSONDecodeError, ValidationError):
            continue
    # Safe fallback if all attempts fail.
    return (
        DecisionReport(
            decision="INCONCLUSIVE",
            confidence="low",
            note="Unable to parse model output. Marked inconclusive.",
        ),
        True,
    )


def normalize_proposal(state: DebateWorkflowState) -> DebateWorkflowState:
    cleaned = " ".join(state["proposal"].split())
    state["proposal"] = cleaned
    state["events"].append({"event_type": "proposal_normalized", "payload": {"proposal": cleaned}})
    return state


def generate_initial_report(state: DebateWorkflowState) -> DebateWorkflowState:
    primary_output = json.dumps(
        {
            "decision": "INCONCLUSIVE",
            "confidence": "low",
            "note": "Initial report generated by workflow scaffold.",
        }
    )
    # Deterministic test hook for retry/fallback coverage.
    if "trigger-parse-failure" in state["proposal"].lower():
        primary_output = "{invalid_json"

    fallback_output = json.dumps(
        {
            "decision": "INCONCLUSIVE",
            "confidence": "low",
            "note": "Fallback report applied after parse failure.",
        }
    )
    report, used_fallback = _parse_report_with_retry([primary_output, fallback_output])

    state["status"] = "created"
    if used_fallback:
        state["events"].append(
            {
                "event_type": "report_parse_fallback_used",
                "payload": {"reason": "primary_output_invalid"},
            }
        )
    state["events"].append(
        {
            "event_type": "decision_report_generated",
            "payload": report.model_dump(),
        }
    )
    return state


def run_debate_workflow(proposal: str) -> DebateWorkflowState:
    graph = StateGraph(DebateWorkflowState)
    graph.add_node("normalize_proposal", normalize_proposal)
    graph.add_node("generate_initial_report", generate_initial_report)
    graph.add_edge(START, "normalize_proposal")
    graph.add_edge("normalize_proposal", "generate_initial_report")
    graph.add_edge("generate_initial_report", END)

    app = graph.compile()
    initial: DebateWorkflowState = {"proposal": proposal, "status": "created", "events": []}
    result = app.invoke(initial)
    return result
