from typing import TypedDict

from langgraph.graph import END, START, StateGraph


class DebateWorkflowState(TypedDict):
    proposal: str
    status: str
    events: list[dict]


def normalize_proposal(state: DebateWorkflowState) -> DebateWorkflowState:
    cleaned = " ".join(state["proposal"].split())
    state["proposal"] = cleaned
    state["events"].append({"event_type": "proposal_normalized", "payload": {"proposal": cleaned}})
    return state


def generate_initial_report(state: DebateWorkflowState) -> DebateWorkflowState:
    state["status"] = "created"
    state["events"].append(
        {
            "event_type": "decision_report_generated",
            "payload": {
                "decision": "INCONCLUSIVE",
                "confidence": "low",
                "note": "Initial report generated by workflow scaffold.",
            },
        }
    )
    return state


def run_debate_workflow(proposal: str) -> DebateWorkflowState:
    graph = StateGraph(DebateWorkflowState)
    graph.add_node("normalize_proposal", normalize_proposal)
    graph.add_node("generate_initial_report", generate_initial_report)
    graph.add_edge(START, "normalize_proposal")
    graph.add_edge("normalize_proposal", "generate_initial_report")
    graph.add_edge("generate_initial_report", END)

    app = graph.compile()
    initial: DebateWorkflowState = {"proposal": proposal, "status": "created", "events": []}
    result = app.invoke(initial)
    return result
